[project]
name = "cf-advanced-evals"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deepeval>=1.0.0",
    "openai>=2.17.0",
    "polars>=1.38.1",
    "pytest>=9.0.2",
    "streamlit>=1.54.0",
]
